import {NoteHook} from "@type/gitlab/NoteHook";

export const MockNoteHook: NoteHook = {
  object_kind: "note",
  event_type: "note",
  user: {
    name: "bot",
    username: "merge.bot",
    avatar_url: "http://gitlab.com/uploads/-/system/user/avatar/82/avatar.png",
  },
  project_id: 23,
  project: {
    id: 23,
    name: "test",
    description: "",
    web_url: "http://gitlab.com/test/my-project",
    avatar_url: "http://gitlab.com/uploads/-/system/project/avatar/23/test.png",
    git_ssh_url: "git@gitlab.com:test/my-project.git",
    git_http_url: "http://gitlab.com/test/my-project.git",
    namespace: "LT",
    visibility_level: 0,
    path_with_namespace: "test/my-project",
    default_branch: "develop",
    ci_config_path: ".gitlab-ci.yml",
    homepage: "http://gitlab.com/test/my-project",
    url: "git@gitlab.com:test/my-project.git",
    ssh_url: "git@gitlab.com:test/my-project.git",
    http_url: "http://gitlab.com/test/my-project.git",
  },
  object_attributes: {
    attachment: null,
    author_id: 82,
    change_position: null,
    commit_id: null,
    created_at: "2018-11-14 09:50:21 UTC",
    discussion_id: "85c18c79997578eedfa769dfa782846159a4030f",
    id: 26005,
    line_code: null,
    note: "test note",
    noteable_id: 4246,
    noteable_type: "MergeRequest",
    original_position: null,
    position: null,
    project_id: 23,
    resolved_at: null,
    resolved_by_id: null,
    resolved_by_push: null,
    st_diff: null,
    system: false,
    type: "DiscussionNote",
    updated_at: "2018-11-14 09:50:21 UTC",
    updated_by_id: null,
    description: "test description",
    url: "http://gitlab.com/test/my-project/merge_requests/1267#note_26005",
  },
  repository: {
    name: "test",
    url: "git@gitlab.com:test/my-project.git",
    description: "",
    homepage: "http://gitlab.com/test/my-project",
  },
  merge_request: {
    assignee_id: null,
    author_id: 34,
    created_at: "2018-11-14 09:07:45 UTC",
    description: "test description",
    head_pipeline_id: 15218,
    id: 4246,
    iid: 1267,
    last_edited_at: "2018-11-14 09:07:49 UTC",
    last_edited_by_id: 34,
    merge_commit_sha: null,
    merge_error: null,
    merge_params: {
      force_remove_source_branch: "1",
    },
    merge_status: "can_be_merged",
    merge_user_id: null,
    merge_when_pipeline_succeeds: false,
    milestone_id: null,
    source_branch: "my-branch",
    source_project_id: 23,
    state: "opened",
    target_branch: "backupNewAgentSubCreate",
    target_project_id: 23,
    time_estimate: 0,
    title: "Add error message if 404",
    updated_at: "2018-11-14 09:50:21 UTC",
    updated_by_id: 82,
    url: "http://gitlab.com/test/my-project/merge_requests/1267",
    source: {
      id: 23,
      name: "test",
      description: "",
      web_url: "http://gitlab.com/test/my-project",
      avatar_url: "http://gitlab.com/uploads/-/system/project/avatar/23/test.png",
      git_ssh_url: "git@gitlab.com:test/my-project.git",
      git_http_url: "http://gitlab.com/test/my-project.git",
      namespace: "LT",
      visibility_level: 0,
      path_with_namespace: "test/my-project",
      default_branch: "develop",
      ci_config_path: ".gitlab-ci.yml",
      homepage: "http://gitlab.com/test/my-project",
      url: "git@gitlab.com:test/my-project.git",
      ssh_url: "git@gitlab.com:test/my-project.git",
      http_url: "http://gitlab.com/test/my-project.git",
    },
    target: {
      id: 23,
      name: "test",
      description: "",
      web_url: "http://gitlab.com/test/my-project",
      avatar_url: "http://gitlab.com/uploads/-/system/project/avatar/23/test.png",
      git_ssh_url: "git@gitlab.com:test/my-project.git",
      git_http_url: "http://gitlab.com/test/my-project.git",
      namespace: "LT",
      visibility_level: 0,
      path_with_namespace: "test/my-project",
      default_branch: "develop",
      ci_config_path: ".gitlab-ci.yml",
      homepage: "http://gitlab.com/test/my-project",
      url: "git@gitlab.com:test/my-project.git",
      ssh_url: "git@gitlab.com:test/my-project.git",
      http_url: "http://gitlab.com/test/my-project.git",
    },
    last_commit: {
      id: "71eb332606c96346e5e9c70270b972bb361b9e38",
      message: "add error message alert if quickRetInput is empty\n",
      timestamp: "2018-11-14T08:00:25Z",
      url: "http://gitlab.com/test/my-project/commit/71eb332606c96346e5e9c70270b972bb361b9e38",
      author: {
        name: "tester",
        email: "tester@xxx",
      },
    },
    work_in_progress: false,
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
  },
};
