import {Label} from "@constants/Label";
import {MergeRequestHook} from "@type/gitlab/MergeRequestHook";

export const MockMergeRequestHook: MergeRequestHook = {
  object_kind: "merge_request",
  event_type: "merge_request",
  user: {
    name: "bot",
    username: "test user",
    avatar_url: "http://gitlab.com/uploads/-/system/user/avatar/82/avatar.png",
  },
  project: {
    id: 23,
    name: "test",
    description: "",
    web_url: "http://gitlab.com/test/my-project",
    avatar_url: "http://gitlab.com/uploads/-/system/project/avatar/23/test.png",
    git_ssh_url: "git@gitlab.com:test/my-project.git",
    git_http_url: "http://gitlab.com/test/my-project.git",
    namespace: "LT",
    visibility_level: 0,
    path_with_namespace: "test/my-project",
    default_branch: "develop",
    ci_config_path: ".gitlab-ci.yml",
    homepage: "http://gitlab.com/test/my-project",
    url: "git@gitlab.com:test/my-project.git",
    ssh_url: "git@gitlab.com:test/my-project.git",
    http_url: "http://gitlab.com/test/my-project.git",
  },
  object_attributes: {
    assignee_id: null,
    author_id: 34,
    created_at: "2018-11-14 09:07:45 UTC",
    description: "test description",
    head_pipeline_id: 15218,
    id: 4246,
    iid: 54088,
    last_edited_at: "2018-11-14 09:07:49 UTC",
    last_edited_by_id: 34,
    merge_commit_sha: "f71d929eed147fee2534f6fefe9afa42c145fc85",
    merge_error: null,
    merge_params: {
      force_remove_source_branch: "1",
    },
    merge_status: "can_be_merged",
    merge_user_id: null,
    merge_when_pipeline_succeeds: false,
    milestone_id: null,
    source_branch: "my-branch",
    source_project_id: 123,
    state: "merged",
    target_branch: "develop",
    target_project_id: 123,
    time_estimate: 0,
    title: "Add error message if 404",
    updated_at: "2018-11-14 09:50:47 UTC",
    updated_by_id: 82,
    url: "http://gitlab.com/test/my-project/merge_requests/1267",
    source: {
      id: 23,
      name: "test",
      description: "",
      web_url: "http://gitlab.com/test/my-project",
      avatar_url: "http://gitlab.com/uploads/-/system/project/avatar/23/test.png",
      git_ssh_url: "git@gitlab.com:test/my-project.git",
      git_http_url: "http://gitlab.com/test/my-project.git",
      namespace: "LT",
      visibility_level: 0,
      path_with_namespace: "test/my-project",
      default_branch: "develop",
      ci_config_path: ".gitlab-ci.yml",
      homepage: "http://gitlab.com/test/my-project",
      url: "git@gitlab.com:test/my-project.git",
      ssh_url: "git@gitlab.com:test/my-project.git",
      http_url: "http://gitlab.com/test/my-project.git",
    },
    target: {
      id: 23,
      name: "test",
      description: "",
      web_url: "http://gitlab.com/test/my-project",
      avatar_url: "http://gitlab.com/uploads/-/system/project/avatar/23/test.png",
      git_ssh_url: "git@gitlab.com:test/my-project.git",
      git_http_url: "http://gitlab.com/test/my-project.git",
      namespace: "LT",
      visibility_level: 0,
      path_with_namespace: "test/my-project",
      default_branch: "develop",
      ci_config_path: ".gitlab-ci.yml",
      homepage: "http://gitlab.com/test/my-project",
      url: "git@gitlab.com:test/my-project.git",
      ssh_url: "git@gitlab.com:test/my-project.git",
      http_url: "http://gitlab.com/test/my-project.git",
    },
    last_commit: {
      id: "71eb332606c96346e5e9c70270b972bb361b9e38",
      message: "add error message alert if quickRetInput is empty\n",
      timestamp: "2018-11-14T08:00:25Z",
      url: "http://gitlab.com/test/my-project/commit/71eb332606c96346e5e9c70270b972bb361b9e38",
      author: {
        name: "tester",
        email: "tester@xxx",
      },
    },
    work_in_progress: false,
    total_time_spent: 0,
    human_total_time_spent: null,
    human_time_estimate: null,
    action: "update",
  },
  labels: [
    {title: Label.REVISION_NEEDED} as any,
  ],
  changes: {
    labels: {
      previous: [
        {
          id: 73,
          title: "waiting auto merge",
          color: "#34495E",
          project_id: null,
          created_at: "2018-11-14 09:38:17 UTC",
          updated_at: "2018-11-14 09:38:17 UTC",
          template: false,
          description: "",
          type: "GroupLabel",
          group_id: 8,
        },
      ],
      current: [

      ],
    },
  },
  repository: {
    name: "test",
    url: "git@gitlab.com:test/my-project.git",
    description: "",
    homepage: "http://gitlab.com/test/my-project",
  },
};
